In [1]:
import pandas as pd



In [6]:
dict_data = {
    'c0':[1,2,3],
    'c1':[4,5,6],
    'c2':[7,8,9],
    'c3':[10,11,12],
    'c4':[13,14,15]
}

df = pd.DataFrame(dict_data)

print(type(df))
print('\n')
print(df)

<class 'pandas.DataFrame'>


   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15


In [12]:
# pandes.Dataframe(2차원배열,
#                  index=행 인덱스 배열,
#                  columns=열 이름 배열)

arr = [
    [15,'남','덕영중'],
    [17,'여','수리중']
]

df = pd.DataFrame(arr,index=['준서','예은'],columns=['나이','성별','학교'])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중


In [1]:
import pandas as pd

arr = [
    [15,'남','덕영중'],
    [17,'여','수리중']
]

df = pd.DataFrame(arr,index=['준서','예은'],columns=['나이','성별','학교'])

print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')


In [2]:
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중


In [3]:
df.index = ['학생1', '학생2']
print(df)

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중


In [5]:
df.columns = ['연령','남녀','소속']
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중


In [8]:
# 행 인덱스 변경: DataFrame객체.rename(index={기존인덱스: 새인덱스})
# 열 인덱스 변경: DataFrame객체.rename(columns={기존이름: 새이름})

import pandas as pd

matrix = [
    [15, '남자', '덕영중'],
    [17, '여', '수리중']
]

df = pd.DataFrame(matrix, index=['준서','예은'], columns=['나이','성별','학교'])
print(df)

    나이  성별   학교
준서  15  남자  덕영중
예은  17   여  수리중


In [10]:
df = df.rename(columns={
    '나이':'연령',
    '성별':'남녀',
    '학교':'소속'
})

print(df)

    연령  남녀   소속
준서  15  남자  덕영중
예은  17   여  수리중


In [ ]:
df = df.rename(index={
    '준서':'학생1',
    '예은':'학생2'
})


    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90


,수학,영어,음악,체육
서준,90,98,95,100
우현,80,89,95,90
인아,70,95,100,90


In [14]:
# 행/열 삭제

# 행 삭제: DataFrame객체.drop(행인덱스 또는 배열, axis=0, axis='index')
# 열 삭제: DataFrame객체.drop(열이름 또는 배열, axis=1, axis='columns')

import pandas as pd

exam_data = {
    '수학' : [ 90,80,70],
    '영어' : [ 98,89,95],
    '음악' : [ 95,95,100],
    '체육' : [ 100,90,90]
}

df = pd.DataFrame(exam_data, index=['서준','우현','인아'])
print(df)
df

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90


,수학,영어,음악,체육
서준,90,98,95,100
우현,80,89,95,90
인아,70,95,100,90


In [17]:
df2 = df.copy()
df2 = df2.drop('우현')
df2

,수학,영어,음악,체육
서준,90,98,95,100
인아,70,95,100,90


In [18]:
df3 = df.copy()
df3 = df.drop(['우현','인아'])
df3

,수학,영어,음악,체육
서준,90,98,95,100


In [19]:
df3 = df.copy()
df3 = df3.drop(['영어','음악'], axis=1)
df3

,수학,체육
서준,90,100
우현,80,90
인아,70,90


In [20]:
df4 = df.copy()
df4 = df4.drop(['영어','음악'], axis='columns')
df4

,수학,체육
서준,90,100
우현,80,90
인아,70,90


In [21]:
import pandas as pd

exam_data = {
    '수학' : [ 90,80,70],
    '영어' : [ 98,89,95],
    '음악' : [ 95,95,100],
    '체육' : [ 100,90,90]
}

df = pd.DataFrame(exam_data, index=['서준','우현','인아'])
df

,수학,영어,음악,체육
서준,90,98,95,100
우현,80,89,95,90
인아,70,95,100,90


In [22]:
labell = df.loc['서준']
print(labell)

수학     90
영어     98
음악     95
체육    100
Name: 서준, dtype: int64


In [31]:
import pandas as pd


# 1. df 라는 이름의 데이터프레임을 만들어 주세요.

data = {
    '이름': ['김철수', '이영희', '박민수', '최지우'],
    '나이': [20, 21, 22, 20],
    '성별': ['남', '여', '남', '여'],
    '수학': [90, 85, 70, 100],
    '영어': [85, 95, 75, 90]
}

df = pd.DataFrame(data)

# 2. 생성된 데이터프레임의 상위 2개 행만 출력하세요.

print(df.head(2))
print('\n')

# 3. 데이터프레임의 요약 정보(컬럼명, 데이터 타입 )을 확인하세요

print(df.index)
print(df.columns)
print('\n')

# 4. '이름' 컬럼을 인덱스로 설정하세요. (기존 df를 수정)

df.set_index('이름',inplace=True)
print(df)
print('\n')

# 5. loc을 사용하여 '이영희'의 '수학' 점수와 '영어' 점수만 추출하세요.

print(df.loc['이영희',['수학','영어']])
print('\n')

# 6. iloc을 사용하여 첫 번째 행부터 두 번째 행까지, 그리고 2번째 열(수학)부터 마지막 열까지 슬라이싱하세요.

print(df.iloc[0:2, 2:])

    이름  나이 성별  수학  영어
0  김철수  20  남  90  85
1  이영희  21  여  85  95


RangeIndex(start=0, stop=4, step=1)
Index(['이름', '나이', '성별', '수학', '영어'], dtype='str')


     나이 성별   수학  영어
이름                 
김철수  20  남   90  85
이영희  21  여   85  95
박민수  22  남   70  75
최지우  20  여  100  90


수학    85
영어    95
Name: 이영희, dtype: int64


     수학  영어
이름         
김철수  90  85
이영희  85  95


In [34]:
import pandas as pd

data = {
    '이름': ['김철수', '이영희', '박민수', '최지우'],
    '나이': [20, 21, 22, 20],
    '성별': ['남', '여', '남', '여'],
    '수학': [90, 85, 70, 100],
    '영어': [85, 95, 75, 90]
}

# 1. 위 데이터로 시리즈 객체 sr을 만들어주세요.

sr = pd.Series(data)
print(sr)
print('\n')

# 2. 시리즈의 인덱스 배열과 데이터값 배열을 각각 추출하여 화면에 출력하세요.

print("index:", sr.index)
print("values:", sr.values)
print('\n')


list_data = ["2010-01-02", 3.14, "ABC", 100, True]

# 3. 위 데이터를 시리즈 객체로 만들어 주세요.

sr2 = pd.Series(list_data)
print(sr2)
print('\n')

# 4. 데이터 타입을 출력헤보세요

print(sr2.dtype)
print('\n')


tup_data = ("영인", "2010-05-01", "여", True)
index_labels = ["이름", "생년월일", "성별", "학생여부"]

# 5. 위 데이터를 시리즈객체로 생성해주세요. 

sr3 = pd.Series(tup_data, index=index_labels)
print(sr3)
print('\n')

# 6. 해당 시리즈의 원소 개수, 형상(shape), 차원을 출력해주세요.

print("size:", sr3.size)
print("shape:", sr3.shape)
print("ndim:", sr3.ndim)
print('\n')

# 7. 위치 기반(정수)으로 첫 번째 원소를 안전하게 조회하는 코드를 작성하세요. (iloc 활용)

print(sr3.iloc[0])
print('\n')

# 8. 라벨 '이름'으로 원소를 조회하는 코드를 작성하세요.

print(sr3.loc['이름'])
print('\n')

# 9. 위치 인덱스 번호 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요. (iloc 권장)

print(sr3.iloc[[1, 2]])
print('\n')

# 10. 라벨 이름 리스트를 활용하여 '생년월일'과 '성별'을 가져오세요.

print(sr3.loc[['생년월일', '성별']])
print('\n')

# 11. 아무 데이터도 전달하지 않은 기본형 빈 시리즈를 생성하세요.

empty = pd.Series()
print(empty)
print('\n')

# 12. 스칼라 값 5와 인덱스 ["a", "b", "c"]를 사용하여 시리즈를 생성하고 출력하세요.

sr4 = pd.Series(5, index=["a", "b", "c"])
print(sr4)


이름    [김철수, 이영희, 박민수, 최지우]
나이        [20, 21, 22, 20]
성별            [남, 여, 남, 여]
수학       [90, 85, 70, 100]
영어        [85, 95, 75, 90]
dtype: object


index: Index(['이름', '나이', '성별', '수학', '영어'], dtype='str')
values: [list(['김철수', '이영희', '박민수', '최지우']) list([20, 21, 22, 20])
 list(['남', '여', '남', '여']) list([90, 85, 70, 100]) list([85, 95, 75, 90])]


0    2010-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object


object


이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object


size: 4
shape: (4,)
ndim: 1


영인


영인


생년월일    2010-05-01
성별               여
dtype: object


생년월일    2010-05-01
성별               여
dtype: object


Series([], dtype: object)


a    5
b    5
c    5
dtype: int64


In [36]:
import numpy as np
 

list1 = [1, 2, 3, 4, 5]
list2 = [
    [1, 2, 3],
    [4, 5, 6]
]


# 1. 아래 주어진 리스트 데이터를 활용하여 각각 1차원 배열 arr1과 2차원 배열 arr2를 생성하고 타입을 출력하세요.

arr1 = np.array(list1)
arr2 = np.array(list2)

print("arr1:", arr1, "/ type:", type(arr1))
print("arr2:", arr2, "/ type:", type(arr2))
print('\n')

# 2. 모든 원소가 0.으로 채워진 크기 5짜리 1차원 배열 zeros 생성

zeros = np.zeros(5)
print(zeros)
print('\n')

# 3. 모든 원소가 1.으로 채워진 크기 $2 \times 3$의 2차원 배열 ones 생성

ones = np.ones((2, 3))
print(ones)
print('\n')

# 4. 1부터 시작하여 2씩 증가하며 10 미만인 정수로 구성된 배열 range_arr 생성

range_arr = np.arange(1, 10, 2)
print(range_arr)
print('\n')


arr3 = np.array([
    [[1, 2],
     [3, 4]], 
    [[5, 6],
     [7, 8]]
])

# 5. 배열 속성(dtype, shape, ndim, size) 출력해주세요

print("dtype:", arr3.dtype)
print("shape:", arr3.shape)
print("ndim:", arr3.ndim)
print("size:", arr3.size)
print('\n')


arr_base = np.array([1, 2, 3, 4, 5, 6])

# 6. 위 1차원 배열을 2차원 배열로 변경해주세요.

arr_2d_reshaped = arr_base.reshape(2, 3)
print(arr_2d_reshaped)
print('\n')


# 7. 배열의 데이터 타입을 실수형(float)으로 변경하여 float_arr에 저장하세요.

float_arr = arr_base.astype(float)
print(float_arr, "/ dtype:", float_arr.dtype)
print('\n')


arr_2d = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

# 8. ravel을 사용해 1차원 배열로 평탄화하여 출력하세요.

print(arr_2d.ravel())
print('\n')

# 9. flatten을 사용해 1차원 배열로 평탄화하여 출력하세요.

print(arr_2d.flatten())
print('\n')

# 10. 축을 바꾸어 3행2열 -> 2행 3열로 만들어주세요 

print(arr_2d.T)
print('\n')


arr_x = np.array([5, 3, 3])
arr_y = np.array([1, 2, 6])

# 11. arr_x와 arr_y의 요소별 합(+)과 요소별 곱(*)을 각각 계산해 출력하세요.

print("합:", arr_x + arr_y)
print("곱:", arr_x * arr_y)
print('\n')

# 12. arr_x가 arr_y보다 큰지 여부를 비교하는 비교 연산 결과를 출력하세요.

print(arr_x > arr_y)
print('\n')

# 13. arr_x에 단일 스칼라 값 2를 곱하여 모든 요소가 2배가 되도록 출력하세요.

print(arr_x * 2)
print('\n')


data = np.array([1, 2, 3, 4, 5])

# 14. data 배열에서 2보다 큰 원소들만 추출하세요.

print(data[data > 2])
print('\n')

# 15. data 배열에서 2보다 크면서 동시에 5보다 작은 원소들만 추출하세요. (비트 연산자 & 활용)

print(data[(data > 2) & (data < 5)])
print('\n')


stats_arr = np.array([1, 2, 3, 4])

# 16. 합계, 평균, 분산, 표준편차, 중앙값을 구하세요  

print("합계:", np.sum(stats_arr))
print("평균:", np.mean(stats_arr))
print("분산:", np.var(stats_arr))
print("표준편차:", np.std(stats_arr))
print("중앙값:", np.median(stats_arr))


arr1: [1 2 3 4 5] / type: <class 'numpy.ndarray'>
arr2: [[1 2 3]
 [4 5 6]] / type: <class 'numpy.ndarray'>


[0. 0. 0. 0. 0.]


[[1. 1. 1.]
 [1. 1. 1.]]


[1 3 5 7 9]


dtype: int64
shape: (2, 2, 2)
ndim: 3
size: 8


[[1 2 3]
 [4 5 6]]


[1. 2. 3. 4. 5. 6.] / dtype: float64


[1 2 3 4 5 6]


[1 2 3 4 5 6]


[[1 4]
 [2 5]
 [3 6]]


합: [6 5 9]
곱: [ 5  6 18]


[ True  True False]


[10  6  6]


[3 4 5]


[3 4]


합계: 10
평균: 2.5
분산: 1.25
표준편차: 1.118033988749895
중앙값: 2.5
