In [1]:
# reshape

import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)

(6,)
<built-in method reshape of numpy.ndarray object at 0x000002D907CCAAF0>


In [4]:
reshaped = arr.reshape((2,3))
print(reshaped.shape)
print(reshaped)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [6]:
# astype
## 데이터타입을 변경한다

arr = np.array([1,2,3,4,5,6])
print(arr.astype(float))

[1. 2. 3. 4. 5. 6.]


In [8]:
# ravel
## 다차원 배열을 1차원 배열로 변경

arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape((2,3))
print(reshaped)

raveled = reshaped.ravel()
print(raveled)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [11]:
# flatten
## 다차원 배열을 1차원 배열로 변경

arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)
flattened = arr.flatten()
print(flattened)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [13]:
# transpose
## 배열의 축을 바꾸는 함수

arr = np.array([
    [1,2,3],
    [4,5,6]
])

transposed = arr.transpose()
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
# 수학연산

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1 + arr2)
print(arr1 * arr2)

[5 7 9]
[ 4 10 18]


In [18]:
# 배열간 비교연산

arr1 = np.array([5,3,3])
arr2 = np.array([1,2,6])

print(arr1 > arr2)
print(arr1 == arr2)
print(arr1 == arr1)

[ True  True False]
[False False False]
[ True  True  True]


In [20]:
# 배열 간의 논리연산

arr1 = np.array([True, False, True])
arr2 = np.array([False, True, True])

print(arr1 & arr2)
print(arr1 | arr2)

[False False  True]
[ True  True  True]


In [22]:
# 배열 간의 집계연산

arr = np.array([1,2,3,4,5])
print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())

15
3.0
1
5


In [23]:
arr = np.array([1,2,3,4,5])
scalar = 2
print(arr * scalar)

[ 2  4  6  8 10]
